var searchData=
[
  ['lm_5fenorm',['lm_enorm',['../lmmin_8cxx.html#af783493b9875c983d0234f9b170c476b',1,'lm_enorm(int n, const double *x):&#160;lmmin.cxx'],['../lmmin_8h.html#a71050d92f91a480357ae67a6d1eb67cf',1,'lm_enorm(int, const double *):&#160;lmmin.cxx']]],
  ['lm_5flmdif',['lm_lmdif',['../lmmin_8cxx.html#a6f929db2bd755b99756287eccd208fd1',1,'lm_lmdif(int m, int n, double *x, double *fvec, double ftol, double xtol, double gtol, int maxfev, double epsfcn, double *diag, int mode, double factor, int *info, int *nfev, double *fjac, int *ipvt, double *qtf, double *wa1, double *wa2, double *wa3, double *wa4, void(*evaluate)(const double *par, int m_dat, const void *data, double *fvec, int *info), void(*printout)(int n_par, const double *par, int m_dat, const void *data, const double *fvec, int printflags, int iflag, int iter, int nfev), int printflags, const void *data):&#160;lmmin.cxx'],['../lmmin_8h.html#a6f929db2bd755b99756287eccd208fd1',1,'lm_lmdif(int m, int n, double *x, double *fvec, double ftol, double xtol, double gtol, int maxfev, double epsfcn, double *diag, int mode, double factor, int *info, int *nfev, double *fjac, int *ipvt, double *qtf, double *wa1, double *wa2, double *wa3, double *wa4, void(*evaluate)(const double *par, int m_dat, const void *data, double *fvec, int *info), void(*printout)(int n_par, const double *par, int m_dat, const void *data, const double *fvec, int printflags, int iflag, int iter, int nfev), int printflags, const void *data):&#160;lmmin.cxx']]],
  ['lm_5flmpar',['lm_lmpar',['../lmmin_8cxx.html#a41ff931f50f8eaa282b7fe5fbc035030',1,'lmmin.cxx']]],
  ['lm_5fprintout_5fstd',['lm_printout_std',['../lmmin_8cxx.html#a411ca31bef588a5d20e1dc38e1588303',1,'lm_printout_std(int n_par, const double *par, int m_dat, const void *data, const double *fvec, int printflags, int iflag, int iter, int nfev):&#160;lmmin.cxx'],['../lmmin_8h.html#a411ca31bef588a5d20e1dc38e1588303',1,'lm_printout_std(int n_par, const double *par, int m_dat, const void *data, const double *fvec, int printflags, int iflag, int iter, int nfev):&#160;lmmin.cxx']]],
  ['lm_5fqrfac',['lm_qrfac',['../lmmin_8cxx.html#aa72b372e483c92753b89a59aa3128b64',1,'lmmin.cxx']]],
  ['lm_5fqrsolv',['lm_qrsolv',['../lmmin_8cxx.html#a0543234dc4a8534dffcec238a778916a',1,'lmmin.cxx']]],
  ['lmcurve_5fevaluate',['lmcurve_evaluate',['../lmcurve_8cxx.html#a7af590242f3a7ce9cd3269dbb1821981',1,'lmcurve.cxx']]],
  ['lmcurve_5ffit',['lmcurve_fit',['../lmcurve_8cxx.html#a5bd65432b5034cbefee67ff4623a787d',1,'lmcurve_fit(int n_par, double *par, int m_dat, const double *t, const double *y, double(*f)(double t, const double *par), const lm_control_struct *control, lm_status_struct *status):&#160;lmcurve.cxx'],['../lmcurve_8h.html#a5bd65432b5034cbefee67ff4623a787d',1,'lmcurve_fit(int n_par, double *par, int m_dat, const double *t, const double *y, double(*f)(double t, const double *par), const lm_control_struct *control, lm_status_struct *status):&#160;lmcurve.cxx']]],
  ['lmmin',['lmmin',['../lmmin_8cxx.html#aef4df2f2a6cef41d253898f8d6b58d10',1,'lmmin(int n_par, double *par, int m_dat, const void *data, void(*evaluate)(const double *par, int m_dat, const void *data, double *fvec, int *info), const lm_control_struct *control, lm_status_struct *status, void(*printout)(int n_par, const double *par, int m_dat, const void *data, const double *fvec, int printflags, int iflag, int iter, int nfev)):&#160;lmmin.cxx'],['../lmmin_8h.html#aef4df2f2a6cef41d253898f8d6b58d10',1,'lmmin(int n_par, double *par, int m_dat, const void *data, void(*evaluate)(const double *par, int m_dat, const void *data, double *fvec, int *info), const lm_control_struct *control, lm_status_struct *status, void(*printout)(int n_par, const double *par, int m_dat, const void *data, const double *fvec, int printflags, int iflag, int iter, int nfev)):&#160;lmmin.cxx']]],
  ['loadrange',['LoadRange',['../classAtTools_1_1AtELossManager.html#aa59c27a1b90398f267aa4331a36d5682',1,'AtTools::AtELossManager']]]
];
